// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "final-project-backend/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// IUserSubscriptionRepository is an autogenerated mock type for the IUserSubscriptionRepository type
type IUserSubscriptionRepository struct {
	mock.Mock
}

// DecrementQuota provides a mock function with given fields: userSubscription, quota
func (_m *IUserSubscriptionRepository) DecrementQuota(userSubscription *models.UserSubscriptions, quota int) (*models.UserSubscriptions, error) {
	ret := _m.Called(userSubscription, quota)

	var r0 *models.UserSubscriptions
	if rf, ok := ret.Get(0).(func(*models.UserSubscriptions, int) *models.UserSubscriptions); ok {
		r0 = rf(userSubscription, quota)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSubscriptions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.UserSubscriptions, int) error); ok {
		r1 = rf(userSubscription, quota)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUserSubscriptions provides a mock function with given fields: userID
func (_m *IUserSubscriptionRepository) GetAllUserSubscriptions(userID int64) ([]*models.UserSubscriptions, error) {
	ret := _m.Called(userID)

	var r0 []*models.UserSubscriptions
	if rf, ok := ret.Get(0).(func(int64) []*models.UserSubscriptions); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserSubscriptions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOngoingUserSubscriptions provides a mock function with given fields: userID
func (_m *IUserSubscriptionRepository) GetOngoingUserSubscriptions(userID int64) ([]*models.UserSubscriptions, error) {
	ret := _m.Called(userID)

	var r0 []*models.UserSubscriptions
	if rf, ok := ret.Get(0).(func(int64) []*models.UserSubscriptions); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserSubscriptions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: userSubscription
func (_m *IUserSubscriptionRepository) Insert(userSubscription *models.UserSubscriptions) (*models.UserSubscriptions, error) {
	ret := _m.Called(userSubscription)

	var r0 *models.UserSubscriptions
	if rf, ok := ret.Get(0).(func(*models.UserSubscriptions) *models.UserSubscriptions); ok {
		r0 = rf(userSubscription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSubscriptions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.UserSubscriptions) error); ok {
		r1 = rf(userSubscription)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userSubscription
func (_m *IUserSubscriptionRepository) Update(userSubscription *models.UserSubscriptions) (*models.UserSubscriptions, error) {
	ret := _m.Called(userSubscription)

	var r0 *models.UserSubscriptions
	if rf, ok := ret.Get(0).(func(*models.UserSubscriptions) *models.UserSubscriptions); ok {
		r0 = rf(userSubscription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserSubscriptions)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.UserSubscriptions) error); ok {
		r1 = rf(userSubscription)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIUserSubscriptionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserSubscriptionRepository creates a new instance of IUserSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserSubscriptionRepository(t mockConstructorTestingTNewIUserSubscriptionRepository) *IUserSubscriptionRepository {
	mock := &IUserSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
