// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "final-project-backend/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// IVoucherRepository is an autogenerated mock type for the IVoucherRepository type
type IVoucherRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *IVoucherRepository) GetAll() ([]*models.Voucher, error) {
	ret := _m.Called()

	var r0 []*models.Voucher
	if rf, ok := ret.Get(0).(func() []*models.Voucher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Voucher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIVoucherRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIVoucherRepository creates a new instance of IVoucherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIVoucherRepository(t mockConstructorTestingTNewIVoucherRepository) *IVoucherRepository {
	mock := &IVoucherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
